# dockerNanny machine setup. Generated by dockerNanny on another computer; run in PowerShell as Administrator.
#
# Before this: `wsl --install -d __DISTRO__`, reboot, open __DISTRO__ once and create your user.
# This script changes only what is missing, so running it again changes nothing: inside __DISTRO__
# (as root, so no sudo prompts) Docker Engine, sshd on port __PORT__, rsync, systemd and that
# computer's public key; in .wslconfig only the lines it needs (mirrored networking, VM stays up),
# keeping yours; firewall rules for the port and a logon task that keeps WSL running. WSL restarts
# only when a setting needs it. Only when chosen in the app: lid and sleep settings while plugged
# in ($keepAwake), and a Public network marked Private ($makePrivate). The Linux part is the same
# script dockerNanny runs when it sets up a computer itself.

$ErrorActionPreference = 'Stop'
$distro = '__DISTRO__'
$port = __PORT__
$memoryChosen = '__MEMORY_CHOSEN__'
$pubkey = '__PUBKEY__'
$keepAwake = $__KEEP_AWAKE__
$makePrivate = $__MAKE_PRIVATE__

function Step($text) { Write-Host "`n==> $text" -ForegroundColor Cyan }

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$isAdmin = ([Security.Principal.WindowsPrincipal]$identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { throw 'Open PowerShell as Administrator and run this again.' }

Step "Checking WSL distro $distro"
# `wsl -l -q` prints UTF-16 with NUL bytes when captured; strip them.
$distros = (wsl.exe -l -q) -replace "`0", '' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
if ($distros -notcontains $distro) {
  throw "WSL distro '$distro' not found. Run: wsl --install -d $distro, reboot, open $distro once to create your user, then run this again."
}
$linuxUser = (wsl.exe -d $distro -- whoami).Trim()
if (-not $linuxUser -or $linuxUser -eq 'root') { throw "Open $distro once and create a normal user first; it becomes the default user." }
Write-Host "Linux user: $linuxUser"

Step 'Inside WSL and in .wslconfig: only what is missing'
if ($linuxUser -notmatch '^[A-Za-z0-9_][A-Za-z0-9._-]*$') { throw "The Linux user name '$linuxUser' cannot be used for ssh." }
$wslconfigLinux = (wsl.exe -d $distro -- wslpath -u ((Join-Path $env:USERPROFILE '.wslconfig') -replace '\\', '/')).Trim()
$halfMemory = [math]::Max(2, [math]::Floor((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 2GB))
# The shared Linux script (host/wsl_ini.sh and host/wsl_setup.sh in dockerNanny).
$shared = @'
__LINUX_SCRIPT__
'@
# That computer's key, which pairing installs when dockerNanny sets up this computer itself.
$keyPart = @'
home=$(getent passwd "$DN_USER" | cut -d: -f6)
install -d -m 700 -o "$DN_USER" -g "$DN_USER" "$home/.ssh"
touch "$home/.ssh/authorized_keys"
grep -qF '@PUBKEY@' "$home/.ssh/authorized_keys" || echo '@PUBKEY@' >> "$home/.ssh/authorized_keys"
chown "$DN_USER":"$DN_USER" "$home/.ssh/authorized_keys"
chmod 600 "$home/.ssh/authorized_keys"
'@
$values = "DN_USER='$linuxUser'`nDN_PORT=$port`nDN_WSLCONFIG='$wslconfigLinux'`nDN_MEMORY='$memoryChosen'`nDN_MEMORY_DEFAULT='${halfMemory}GB'`n"
$bash = $values + $shared + "`n" + $keyPart.Replace('@PUBKEY@', $pubkey)
$tmp = Join-Path $env:TEMP 'dockernanny-setup.sh'
[IO.File]::WriteAllText($tmp, ($bash -replace "`r`n", "`n"), (New-Object Text.UTF8Encoding($false)))
$tmpLinux = (wsl.exe -d $distro -- wslpath -u ($tmp -replace '\\', '/')).Trim()
$output = wsl.exe -d $distro -u root -- sh $tmpLinux
$failed = $LASTEXITCODE -ne 0
$output | ForEach-Object { Write-Host $_ }
if ($failed) { throw 'The Linux part failed; see the output above.' }
$changes = @($output | Where-Object { $_ -like 'dockernanny-changed: *' })
if ($changes.Count -eq 0) { Write-Host 'Everything was already there.' }

Step "Opening port $port in the firewall"
$public = Get-NetConnectionProfile | Where-Object { $_.NetworkCategory -eq 'Public' }
if ($public -and $makePrivate) {
  $public | Set-NetConnectionProfile -NetworkCategory Private
  Write-Host "Network '$($public.Name -join ', ')' was marked Public (which blocks everything); it is now Private."
} elseif ($public) {
  Write-Host "Network '$($public.Name -join ', ')' is marked Public, which blocks the firewall rule. Mark it Private in Windows settings if you trust it." -ForegroundColor Yellow
}
if (-not (Get-NetFirewallRule -DisplayName 'dockerNanny SSH' -ErrorAction SilentlyContinue)) {
  New-NetFirewallRule -DisplayName 'dockerNanny SSH' -Direction Inbound -Protocol TCP -LocalPort $port -Action Allow -Profile Private, Domain | Out-Null
}
try {
  if (-not (Get-NetFirewallHyperVRule -Name 'dockerNannySsh' -ErrorAction SilentlyContinue)) {
    New-NetFirewallHyperVRule -Name 'dockerNannySsh' -DisplayName 'dockerNanny SSH' -Direction Inbound -VMCreatorId '{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}' -Protocol TCP -LocalPorts $port | Out-Null
  }
} catch {
  Write-Host 'Hyper-V firewall cmdlets are not on this Windows build; skipped.' -ForegroundColor Yellow
}

if ($keepAwake) {
  Step 'Keeping this machine awake with the lid closed while plugged in'
  powercfg /setacvalueindex SCHEME_CURRENT SUB_BUTTONS LIDACTION 0 | Out-Null
  powercfg /setactive SCHEME_CURRENT | Out-Null
  powercfg /change standby-timeout-ac 0 | Out-Null
} else {
  Write-Host "`nPower settings left as they are: this machine sleeps as it did, and is unreachable while asleep."
}

Step 'Keeping WSL running after every logon'
# `-e` instead of `--`: schtasks reads a bare `--` as one of its own options.
$keepAlive = "wsl.exe -d $distro -e sleep infinity"
schtasks.exe /Create /TN 'dockerNanny WSL' /SC ONLOGON /RL HIGHEST /F /TR "powershell.exe -WindowStyle Hidden -NoProfile -Command $keepAlive" | Out-Null

Step 'Restarting WSL only if a setting needs it'
# wsl --shutdown stops every distribution (Docker Desktop's too), so only a changed .wslconfig uses it.
$restarted = $true
if ($changes -match '^dockernanny-changed: \.wslconfig$') {
  Write-Host '.wslconfig changed, which WSL reads when it starts: wsl --shutdown'
  wsl.exe --shutdown
} elseif ($changes -match '^dockernanny-changed: wsl\.conf') {
  Write-Host "/etc/wsl.conf changed, which $distro reads when it starts: restarting $distro only"
  wsl.exe --terminate $distro
} else {
  Write-Host 'Nothing needs a restart.'
  $restarted = $false
}
if ($restarted) {
  Start-Sleep -Seconds 3
  Start-Process -WindowStyle Hidden powershell.exe -ArgumentList '-NoProfile', '-Command', $keepAlive
  Start-Sleep -Seconds 10
}
$listening = (wsl.exe -d $distro -- sh -c "ss -ltn | grep -q ':$port ' && echo yes || echo no").Trim()
$dockerOk = (wsl.exe -d $distro -- sh -c "docker version --format '{{.Server.Version}}' 2>/dev/null || echo not-running").Trim()
Write-Host "sshd listening on $port`: $listening    Docker Engine: $dockerOk"
if ($listening -ne 'yes') { Write-Host "sshd is not listening yet. Reboot Windows once, then check with: wsl -d $distro -- ss -ltn" -ForegroundColor Yellow }

Step 'Done. In dockerNanny on the other computer, click Add machine and enter:'
$addresses = Get-NetIPAddress -AddressFamily IPv4 |
  Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.InterfaceAlias -notlike '*vEthernet*' } |
  ForEach-Object { "$($_.IPAddress) ($($_.InterfaceAlias))" }
Write-Host "  Address: $($addresses -join '  or  ')"
Write-Host "  User:    $linuxUser"
Write-Host "  Port:    $port"
