//! Every conversation with a remote goes through here: a generated ssh config
//! with one Host block per machine, and commands built from it. Nothing else
//! in the app spawns ssh directly. The processes themselves are started
//! through `tools` (inside WSL on Windows) and run as a `Job` or to an `Output`.

use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use tokio::process::Command;

use crate::job::{self, Job, Line, Output};
use crate::machine::Machine;
use crate::tools;

const CONFIG_FILE: &str = "ssh_config";
/// Two files, each with one writer: ssh adds the keys it learns to
/// known_hosts, the app writes the keys learned at pairing to pinned_hosts.
/// Neither rewrites the other's, so no key can be lost between them.
const KNOWN_HOSTS_FILE: &str = "known_hosts";
const PINNED_HOSTS_FILE: &str = "pinned_hosts";
/// One writer at a time for the files above: adding, removing and pairing
/// machines can each rewrite them.
static WRITING: std::sync::Mutex<()> = std::sync::Mutex::new(());
/// Long enough for `compose stop` of a big stack; streamed work (rsync,
/// compose up, logs, copies) runs as a `Job` and has no such limit.
const RUN_LIMIT: Duration = Duration::from_secs(120);

#[derive(Clone)]
pub struct Ssh {
    /// The app folder on this computer; the tools may see it elsewhere (`tools::home`).
    home: PathBuf,
}

impl Ssh {
    pub fn new(home: &Path) -> anyhow::Result<Self> {
        // Control sockets live in short paths on purpose: a unix socket path
        // is capped at 104 bytes on macOS, and rsync's `-e` cannot carry spaces.
        // %C expands to a 40 character hash, and while ssh creates the socket
        // it adds a 17 character temporary suffix; the whole path must stay
        // under 104 bytes or ssh refuses to start.
        let tools_home = tools::home(home);
        let longest_socket = tools_home.len() + "/cm/".len() + 40 + 17;
        anyhow::ensure!(
            longest_socket < 104,
            "home folder path is too long for ssh control sockets: {tools_home} (set DOCKERNANNY_HOME to a shorter path)"
        );
        Ok(Self { home: home.to_path_buf() })
    }

    /// Makes the tools' folders and writes the config. At start and after
    /// the WSL distribution changes; on Windows it fails while WSL is missing,
    /// which the caller logs rather than refusing to start.
    pub fn prepare(&self, machines: &[Machine]) -> anyhow::Result<()> {
        tools::make_private_dirs(&self.home, &["cm", "fwd"])?;
        self.write_config(machines)
    }

    /// The config as ssh reads it (inside WSL on Windows).
    pub fn config_path(&self) -> String {
        format!("{}/{CONFIG_FILE}", tools::home(&self.home))
    }

    /// Records the host key learned at pairing, in the app's own file. One
    /// line per machine; a machine paired again replaces its old line.
    pub fn pin_host_key(&self, machine: &Machine, key_type: &str, blob: &str) -> anyhow::Result<()> {
        let _writing = WRITING.lock().expect("ssh files lock");
        let existing = std::fs::read_to_string(self.home.join(PINNED_HOSTS_FILE)).unwrap_or_default();
        let text = merge_known_hosts(&existing, &known_hosts_name(machine), key_type, blob);
        tools::write_file(&self.home, PINNED_HOSTS_FILE, &text)
    }

    /// The folder of the port bridges' control sockets, as ssh sees it.
    pub fn forward_dir(&self) -> String {
        format!("{}/fwd", tools::home(&self.home))
    }

    /// Regenerates the whole config from the machine list. The user's own
    /// `~/.ssh/config` is never touched; they may `Include` this file if they
    /// want the same aliases in their terminal.
    pub fn write_config(&self, machines: &[Machine]) -> anyhow::Result<()> {
        let _writing = WRITING.lock().expect("ssh files lock");
        let tools_home = tools::home(&self.home);
        let places = Places {
            control: format!("{tools_home}/cm/%C"),
            known_hosts: format!("{tools_home}/{KNOWN_HOSTS_FILE}"),
            pinned_hosts: format!("{tools_home}/{PINNED_HOSTS_FILE}"),
        };
        let mut text = String::from("# Generated by dockerNanny. Edit machines in the app, not here.\n");
        for machine in machines {
            // One unreadable key must not take every other machine's entry with it.
            let key = tools::key_for_tools(&self.home, &machine.id, &machine.key_path).unwrap_or_else(|err| {
                tracing::warn!("key for {}: {err:#}", machine.name);
                tools::path(Path::new(&machine.key_path))
            });
            text.push_str(&host_block(machine, &key, &places));
        }
        tools::write_file(&self.home, CONFIG_FILE, &text)
    }

    /// `ssh -F <config> <alias> sh -l`: the script arrives on stdin, so no
    /// quoting is ever needed, and the login shell gives the remote's real PATH
    /// (docker in /usr/local/bin on a Mac, ~/.local/bin on Linux).
    pub fn command(&self, alias: &str) -> Command {
        // Off unless RUST_LOG asks for it: counts what the app sends to machines.
        tracing::debug!(target: "dockernanny::remote", "ssh {alias}");
        let mut cmd = tools::unix("ssh");
        cmd.arg("-F").arg(self.config_path()).arg(alias).arg("sh").arg("-l");
        cmd
    }

    /// `ssh -F <config> <alias> "sh -lc '<command>'"`: for the rare case where
    /// stdin must carry data instead of the script (volume streams). The login
    /// shell gives the machine's real PATH; the command is refused if it could
    /// break out of the quotes.
    pub fn piped_command(&self, alias: &str, remote: &str) -> anyhow::Result<Command> {
        let breaks_quoting = remote.contains('\'') || remote.contains('\n');
        anyhow::ensure!(!breaks_quoting, "remote command contains characters that are not allowed");
        let mut cmd = tools::unix("ssh");
        cmd.arg("-F").arg(self.config_path()).arg(alias).arg(format!("sh -lc '{remote}'"));
        Ok(cmd)
    }

    /// What rsync's `-e` receives. No spaces anywhere in the path by design.
    pub fn rsync_transport(&self) -> String {
        format!("ssh -F {}", self.config_path())
    }

    /// Runs one remote script to completion and captures both streams, for
    /// at most `RUN_LIMIT`: a machine whose Docker hangs while ssh stays up
    /// must not leave a card spinning forever.
    pub async fn run(&self, alias: &str, script: &str) -> anyhow::Result<Output> {
        self.run_within(alias, script, RUN_LIMIT).await
    }

    /// `run` with the caller's own limit (a poll wants an answer quickly).
    /// Giving up ends the command on the machine too, see `ends_with_the_connection`.
    pub async fn run_within(&self, alias: &str, script: &str, limit: Duration) -> anyhow::Result<Output> {
        let script = ends_with_the_connection(script);
        match tokio::time::timeout(limit, job::run_with_stdin(self.command(alias), &script)).await {
            Ok(result) => result,
            Err(_) => anyhow::bail!("the machine did not answer within {} s", limit.as_secs()),
        }
    }

    /// Like `run`, but streams output lines as they arrive and can be
    /// cancelled; cancelling ends the command on the machine too.
    pub fn job(&self, alias: &str, script: &str, on_line: impl FnMut(Line) + Send + 'static) -> anyhow::Result<Job> {
        Job::spawn(self.command(alias), Some(ends_with_the_connection(script)), on_line)
    }

    /// Asks the master on `socket` (the shared one when None) to exit. Used
    /// when a machine is removed and at exit.
    pub fn exit_master(&self, alias: &str, socket: Option<&str>) {
        self.control_master(alias, socket, "exit");
    }

    /// Asks the shared master to take no new sessions, while the ones on it
    /// (a copy, a log follow) finish. The next command logs in afresh, so a
    /// check sees what changed on the machine since, such as a new group:
    /// a login keeps the groups it started with.
    pub fn retire_master(&self, alias: &str) {
        self.control_master(alias, None, "stop");
    }

    fn control_master(&self, alias: &str, socket: Option<&str>, command: &str) {
        let mut cmd = tools::unix_std("ssh");
        cmd.arg("-F").arg(self.config_path());
        if let Some(socket) = socket {
            cmd.arg("-S").arg(socket);
        }
        let _ = cmd.args(["-O", command, alias]).stdin(Stdio::null()).stdout(Stdio::null()).stderr(Stdio::null()).status();
    }
}

/// Without a terminal, sshd does not end a command when the connection goes:
/// a killed ssh here left `compose logs -f` running there for good, and a
/// hung probe piled up. So the script runs in the background while a watcher
/// reads this computer's side of the connection, which this computer keeps
/// open until the script is done or it gives up; at end of input the watcher
/// ends the whole process group.
///
/// The shell gives a background command /dev/null as stdin unless it is
/// redirected explicitly, so the connection is first copied to descriptor 3
/// and the watcher reads that. The script's own stdin is /dev/null, so
/// nothing competes with the watcher, and everything after the script is
/// one line, read in full before the watcher starts.
pub fn ends_with_the_connection(script: &str) -> String {
    format!("exec 3<&0\n(\n{script}\n) </dev/null & w=$!; ( cat <&3 >/dev/null; kill 0 ) >/dev/null 2>&1 & wait $w; c=$?; exit $c\n")
}

/// The known_hosts text with one line for `marker`, replacing any older one.
fn merge_known_hosts(existing: &str, marker: &str, key_type: &str, blob: &str) -> String {
    let mut lines: Vec<&str> = existing.lines().filter(|line| line.split_whitespace().next() != Some(marker)).collect();
    let fresh = format!("{marker} {key_type} {blob}");
    lines.push(&fresh);
    lines.join("\n") + "\n"
}

/// How known_hosts names this machine: `[host]:port`, or just the host on 22.
pub fn known_hosts_name(machine: &Machine) -> String {
    if machine.port == 22 {
        machine.host.clone()
    } else {
        format!("[{}]:{}", machine.host, machine.port)
    }
}

/// Where the config points ssh, as ssh sees those paths.
struct Places {
    control: String,
    known_hosts: String,
    pinned_hosts: String,
}

fn host_block(machine: &Machine, key: &str, places: &Places) -> String {
    // A pinned machine trusts only the key learned at pairing; a hand-added
    // one trusts the first key it sees, the usual ssh behaviour. ssh reads
    // both files and adds what it learns to the first; neither is the
    // user's own.
    let checking = if machine.pinned { "yes" } else { "accept-new" };
    let trust = format!("UserKnownHostsFile {} {}\n  StrictHostKeyChecking {checking}", places.known_hosts, places.pinned_hosts);
    format!(
        "\nHost {alias}\n  \
           HostName {host}\n  \
           User {user}\n  \
           Port {port}\n  \
           IdentityFile \"{key}\"\n  \
           IdentitiesOnly yes\n  \
           BatchMode yes\n  \
           {trust}\n  \
           ConnectTimeout 5\n  \
           ControlMaster auto\n  \
           ControlPath {control}\n  \
           ControlPersist 60s\n  \
           ServerAliveInterval 15\n  \
           ServerAliveCountMax 2\n  \
           LogLevel ERROR\n",
        alias = machine.alias(),
        host = machine.host,
        user = machine.user,
        port = machine.port,
        control = places.control,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn machine(port: u16, pinned: bool) -> Machine {
        Machine {
            id: "abc".into(),
            name: "studio".into(),
            user: "alex".into(),
            host: "192.0.2.15".into(),
            port,
            key_path: "/home/alex/.ssh/id_ed25519".into(),
            docker_context: false,
            pinned,
        }
    }

    fn places() -> Places {
        Places { control: "/h/cm/%C".into(), known_hosts: "/h/known_hosts".into(), pinned_hosts: "/h/pinned_hosts".into() }
    }

    #[test]
    fn a_remote_script_ends_with_the_connection() {
        let wrapped = ends_with_the_connection("echo one\ndocker compose logs -f");
        assert!(wrapped.starts_with("exec 3<&0\n(\necho one\ndocker compose logs -f\n) </dev/null & w=$!; "), "{wrapped}");
        assert!(
            wrapped.contains("( cat <&3 >/dev/null; kill 0 ) >/dev/null 2>&1 &"),
            "the watcher reads the copied connection and holds no output pipe"
        );
        assert!(wrapped.ends_with("wait $w; c=$?; exit $c\n"), "the shell needs no end of input to finish");
    }

    #[test]
    fn known_hosts_names_follow_ssh_convention() {
        assert_eq!(known_hosts_name(&machine(22, true)), "192.0.2.15");
        assert_eq!(known_hosts_name(&machine(2222, true)), "[192.0.2.15]:2222");
    }

    #[test]
    fn pinned_machines_trust_only_the_pinned_key() {
        let pinned = host_block(&machine(2222, true), "/k", &places());
        assert!(pinned.contains("StrictHostKeyChecking yes"));
        assert!(
            pinned.contains("UserKnownHostsFile /h/known_hosts /h/pinned_hosts"),
            "ssh adds to the first file, the app writes the second"
        );
        assert!(pinned.contains("IdentityFile \"/k\""));
        let loose = host_block(&machine(2222, false), "/k", &places());
        assert!(loose.contains("StrictHostKeyChecking accept-new"));
        assert!(loose.contains("UserKnownHostsFile /h/known_hosts"), "a hand-added machine's key lands in the app's file too");
    }

    #[test]
    fn pinning_replaces_the_old_line_for_the_same_machine() {
        let first = merge_known_hosts("", "[192.0.2.15]:2222", "ssh-ed25519", "AAAAold");
        let with_other = merge_known_hosts(&first, "studio.local", "ssh-rsa", "BBBB");
        let replaced = merge_known_hosts(&with_other, "[192.0.2.15]:2222", "ssh-ed25519", "AAAAnew");
        assert_eq!(replaced, "studio.local ssh-rsa BBBB\n[192.0.2.15]:2222 ssh-ed25519 AAAAnew\n");
    }
}
